### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by VitaliiVKalinin** [neurobin/MT7630E#96]
# System info

Entry | Details
----- | -------
OS | Linux Mint 19.2
Kernel version | 4.15.0-58-generic

When I'm trying to execute ./bpatch I get this error:
*** Copying configuration...
./bpatch: line 164: cd: drivers/bluetooth/: No such file or directory
----------------------------------------------------------------------------------
When I executing ./test I get these errors:
insmod: ERROR: could not insert module ./rt2x00/mt7630e.ko: File exists
insmod: ERROR: could not insert module ./btloader/mt76xx.ko: File exists

What should I do? 
Thanks

**Comment by drotor** [comment]
I think problem begins when a different source is automatically selected, i.e.
_Picking 'linux-signed' as source package instead of 'linux-image-4.15.0-63-generic'_.
Others suggested using 
_sudo apt-get source linux_ 
instead of 
_apt-get source linux-image-$(uname -r)_ 
to get the kernel source code manually. Ran into problems even doing this only to have the modified driver rejected at boot time because of mismatched version magic numbers. Finally got the kernel from kernel.org .
     HOWEVER, the best solution can be found at
_**https://github.com/jeremyb31/newbtfix-4.15**_
It is simply to follow and install.

**Comment by VitaliiVKalinin** [comment]
> I think problem begins when a different source is automatically selected, i.e.
> _Picking 'linux-signed' as source package instead of 'linux-image-4.15.0-63-generic'_.
> Others suggested using
> _sudo apt-get source linux_
> instead of
> _apt-get source linux-image-$(uname -r)_
> to get the kernel source code manually. Ran into problems even doing this only to have the modified driver rejected at boot time because of mismatched version magic numbers. Finally got the kernel from kernel.org .
> HOWEVER, the best solution can be found at
> _**https://github.com/jeremyb31/newbtfix-4.15**_
> It is simply to follow and install.

Thank you very much!
